% Auto-generated by cameraCalibrator app on 26-Feb-2018
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\doorn\Google Drive\Sensor paper journal publication\Software\Matlab\Camera Calibration\Calibration webcam\Image3.png',...
    'C:\Users\doorn\Google Drive\Sensor paper journal publication\Software\Matlab\Camera Calibration\Calibration webcam\Image4.png',...
    'C:\Users\doorn\Google Drive\Sensor paper journal publication\Software\Matlab\Camera Calibration\Calibration webcam\Image5.png',...
    'C:\Users\doorn\Google Drive\Sensor paper journal publication\Software\Matlab\Camera Calibration\Calibration webcam\Image6.png',...
    'C:\Users\doorn\Google Drive\Sensor paper journal publication\Software\Matlab\Camera Calibration\Calibration webcam\Image7.png',...
    'C:\Users\doorn\Google Drive\Sensor paper journal publication\Software\Matlab\Camera Calibration\Calibration webcam\Image8.png',...
    'C:\Users\doorn\Google Drive\Sensor paper journal publication\Software\Matlab\Camera Calibration\Calibration webcam\Image11.png',...
    'C:\Users\doorn\Google Drive\Sensor paper journal publication\Software\Matlab\Camera Calibration\Calibration webcam\Image12.png',...
    'C:\Users\doorn\Google Drive\Sensor paper journal publication\Software\Matlab\Camera Calibration\Calibration webcam\Image13.png',...
    'C:\Users\doorn\Google Drive\Sensor paper journal publication\Software\Matlab\Camera Calibration\Calibration webcam\Image14.png',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 30;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', true, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

cameraParams

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
